parameters:
  - $ref: ../components/parameters/form.yaml
  - $ref: ../components/parameters/org.yaml
  - $ref: ../components/parameters/dataset.yaml
  - $ref: ../components/parameters/version.yaml
  - $ref: ../components/parameters/service.yaml
  - $ref: ../components/parameters/traceparent.yaml
  - $ref: ../components/parameters/tracestate.yaml
  - $ref: ../components/parameters/If-None-Match.yaml
  - $ref: ../components/parameters/Accept-Language.yaml

get:
  tags:
    - services
put:
  tags:
    - services
post:
  tags:
    - services
delete:
  tags:
    - services
options:
  tags:
    - services
head:
  tags:
    - services
patch:
  tags:
    - services
trace:
  tags:
    - services
